1. Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5
matrix.

In [1]:
import numpy as np

arr = np.arange(1, 11)
matrix = arr.reshape(2, 5)

print(matrix)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


2. Create a numpy array containing the numbers from 1 to 20, and then extract the
elements between the 5th and 15th index.

In [4]:
import numpy as np

arr = np.arange(1, 21)
print(f"Array : {arr}")
subset = arr[5:16]

print(f"New Array: {subset}")


Array : [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
New Array: [ 6  7  8  9 10 11 12 13 14 15 16]


3. How to compute the mean, median, and standard deviation of a numpy array?Use the
array you created above

In [6]:
import numpy as np

arr = np.arange(1, 21)
subset = arr[5:16]
print(f"New Array: {subset}")

mean_val = np.mean(subset)
median_val = np.median(subset)
std_val = np.std(subset)

print("Mean:", mean_val)
print("Median:", median_val)
print("Standard Deviation:", std_val)


New Array: [ 6  7  8  9 10 11 12 13 14 15 16]
Mean: 11.0
Median: 11.0
Standard Deviation: 3.1622776601683795


4. Write a NumPy program that creates a 2D array x of shape (3, 4) and a 1D array y of
shape (4,). Subtract y from each row of x using broadcasting.

In [7]:
import numpy as np

x = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
y = np.array([1, 2, 3, 4])

result = x - y
print(result)


[[0 0 0 0]
 [4 4 4 4]
 [8 8 8 8]]


5. Create a dataframe with the following columns: name, age, and gender. The dataframe
should have 10 rows of data. (Score: 2)

    a) Add a new column to the data frame created in question 1, called occupation.
    The values for this column should be Programmer, Manager, and Analyst,
    corresponding to the rows in the dataframe. (Score: 1)
   
    b) Select the rows of the dataframe where the age is greater than or equal to 30.
    (Score: 1)
   
    c) Convert this dataframe to a CSV file and read that CSV file, and finally display
    the contents. (Score: 1)

In [9]:
import pandas as pd

data = {
    "name": ["Alice", "Bob", "Charlie", "David", "Eva",
             "Frank", "Grace", "Helen", "Ian", "Julia"],
    "age": [25, 32, 28, 45, 30, 22, 35, 40, 27, 31],
    "gender": ["F", "M", "M", "M", "F", "M", "F", "F", "M", "F"]
}
df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

#Add a new column to the data frame created in question 1, called occupation. The values for this column should be Programmer, Manager, and Analyst, corresponding to the rows in the dataframe.
occupations = ["Programmer", "Manager", "Analyst",
               "Programmer", "Manager", "Analyst",
               "Programmer", "Manager", "Analyst", "Programmer"]
df["occupation"] = occupations
print("\nDataFrame with Occupation:\n", df)

#Select the rows of the dataframe where the age is greater than or equal to 30.
age_filter = df[df["age"] >= 30]
print("\nRows where age >= 30:\n", age_filter)

# Convert this dataframe to a CSV file and read that CSV file, and finally display the contents.
df.to_csv("people.csv", index=False)   
df_from_csv = pd.read_csv("people.csv") 
print("\nDataFrame read from CSV:\n", df_from_csv)


Original DataFrame:
       name  age gender
0    Alice   25      F
1      Bob   32      M
2  Charlie   28      M
3    David   45      M
4      Eva   30      F
5    Frank   22      M
6    Grace   35      F
7    Helen   40      F
8      Ian   27      M
9    Julia   31      F

DataFrame with Occupation:
       name  age gender  occupation
0    Alice   25      F  Programmer
1      Bob   32      M     Manager
2  Charlie   28      M     Analyst
3    David   45      M  Programmer
4      Eva   30      F     Manager
5    Frank   22      M     Analyst
6    Grace   35      F  Programmer
7    Helen   40      F     Manager
8      Ian   27      M     Analyst
9    Julia   31      F  Programmer

Rows where age >= 30:
     name  age gender  occupation
1    Bob   32      M     Manager
3  David   45      M  Programmer
4    Eva   30      F     Manager
6  Grace   35      F  Programmer
7  Helen   40      F     Manager
9  Julia   31      F  Programmer

DataFrame read from CSV:
       name  age gender  occupa